---
book_repo: pivotal-cf/docs-book-wiki
layout_repo: pivotal-cf/docs-layout-repo

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

elastic_search: true

public_host: docs-wiki.cfapps.io

products:
  - id: pcf
    subnav_root: wiki/index.html

sections:
- repository:
    name: pivotal-cf-experimental/docs-wiki-internal
  directory: wiki
  product_id: pcf
  product_info:
    use_local_header: true
    local_header_img: /images/cloud_rings.png
    local_header_title: Docs Wiki
    search_placeholder: Search Docs Wiki
    url_prefix: wiki

template_variables:                             # optional

book_title: Docs Wiki