---
book_repo: pivotal-cf/docs-book-wiki
layout_repo: pivotal-cf/docs-layout-repo

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

elastic_search: true

public_host: hello

products:
  - id: pcf
    subnav_root: wiki/index.html

sections:
- repository:
    name: pivotal-cf-experimental/docs-wiki-internal
  directory: wiki
  product_id: pcf

template_variables:                             # optional

book_title: Docs Wiki